"""empty message

Revision ID: 92bf3f5bb060
Revises: 
Create Date: 2021-12-08 21:20:25.594782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bf3f5bb060'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payable',
    sa.Column('bar_code', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('bar_code')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=200), nullable=False),
    sa.Column('card_number', sa.String(length=200), nullable=True),
    sa.Column('bar_code', sa.String(length=1024), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('payable')
    # ### end Alembic commands ###
